apiVersion: v1
kind: ServiceAccount
metadata:
  name: inference-service-sa
  namespace: default
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::715428147916:role/inference-service-irsa-role
