apiVersion: v1
kind: ServiceAccount
metadata:
  name: user-service-sa
  namespace: user-service
  labels:
    app: user-service
  annotations:
    eks.amazonaws.com/role-arn: arn:aws:iam::715428147916:role/UserServicePodRole
automountServiceAccountToken: true
# IRSA 방식으로 자동 주입 활성화